#!/bin/bash

./buildwords


# do a bit of section demotion and replace index with indw for the automatic
# words.
sed s/\\\\index/\\\\indw/g allwords.tex |\
    sed s/section\{/subsection\{/g >autowords.tex
pdflatex manual.tex
makeindex manual
pdflatex manual.tex
pdflatex manual.tex
